In [59]:
import numpy as np

In [60]:
n_traj = 3;
n_frame = 11;

In [61]:
traj = np.random.randint(low=0,high=10,size=n_traj)
print(traj)

ratio = n_frame/n_traj
print(ratio)

traj_adj = np.zeros(n_frame)

ratio = int(ratio)
print(ratio)
n_req_pad = n_frame - ratio*n_traj

# pre-padding
idx=0
for i in range(n_traj) : 
    print(idx)
    if i < n_req_pad : 
        len_rep = ratio +1
    else :
        len_rep = ratio

    traj_adj[idx:idx+len_rep]=traj[i]
    idx+=len_rep
print(traj_adj)

[6 7 8]
3.6666666666666665
3
0
4
8
[6. 6. 6. 6. 7. 7. 7. 7. 8. 8. 8.]


In [62]:
traj2 = np.repeat(traj,ratio)
print(traj2.shape)
print(traj2)

(9,)
[6 6 6 7 7 7 8 8 8]


In [63]:
traj3 = np.full(traj,(n_frame))
print(traj3.shape)

(6, 7, 8)


## traj with pos

In [87]:
traj = np.random.rand(3,2)
print(traj.shape)
print(traj)

traj = np.tile(traj,(2,1,1))
print(traj.shape)
print(traj)

pos = np.zeros((2,2))
print(pos.shape)
pos = np.expand_dims(pos,1)
print(pos.shape)
pos[0,:,:] = 10
pos[1,:,:] = 100

traj = traj+ pos

print(traj.shape)
print(traj)

(3, 2)
[[0.151969   0.0944871 ]
 [0.6283427  0.50171377]
 [0.9952515  0.10394967]]
(2, 3, 2)
[[[0.151969   0.0944871 ]
  [0.6283427  0.50171377]
  [0.9952515  0.10394967]]

 [[0.151969   0.0944871 ]
  [0.6283427  0.50171377]
  [0.9952515  0.10394967]]]
(2, 2)
(2, 1, 2)
(2, 3, 2)
[[[ 10.151969    10.0944871 ]
  [ 10.6283427   10.50171377]
  [ 10.9952515   10.10394967]]

 [[100.151969   100.0944871 ]
  [100.6283427  100.50171377]
  [100.9952515  100.10394967]]]


In [ ]:
pos = []