In [1]:
import numpy as np

In [6]:
a = np.ones((4,23))
b = np.ones((4,23))
print(a.shape)
print(b.shape)

(4, 23)
(4, 23)


In [11]:
aa = aa/np.max(np.abs(aa))
print(aa.shape)

(4,)


In [12]:
aa = np.sum(np.power(a,2),axis=1)
print(aa.shape)

(4,)


In [13]:
aa = a* 4
print(aa.shape)

(4, 23)


In [15]:
x = []
x.append(a)
x.append(b)
x

[array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]]),
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])]

In [20]:
xx = np.sum(x,axis=0)
print(xx.shape)
print(xx)

(4, 23)
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


## Dim Adjust

In [21]:
len_target = 10

In [39]:
short = np.random.rand(4,3)
over  = np.random.rand(11,2)
fit   = np.random.rand(10,4)

In [40]:
def adjust(x):
    if len(x) < len_target :
        short = len_target - len(x)
        x = np.pad(x,((0,short),(0,0)))
    elif len(x) > len_target :
        over = len(x) - len_target
        x = x[:-over]
    else :
        pass
    return x

In [41]:
o = adjust(short)
oo = adjust(over)
ooo = adjust(fit)
print(o.shape)
print(oo.shape)
print(ooo.shape)


(10, 3)
(10, 2)
(10, 4)
